/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsTemporaryEmailRouteImport } from './routes/what-is-temporary-email'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TempMailForTiktokRouteImport } from './routes/temp-mail-for-tiktok'
import { Route as TempMailForOtpRouteImport } from './routes/temp-mail-for-otp'
import { Route as TempMailForNetflixRouteImport } from './routes/temp-mail-for-netflix'
import { Route as TempMailForInstagramRouteImport } from './routes/temp-mail-for-instagram'
import { Route as TempMailForAmazonRouteImport } from './routes/temp-mail-for-amazon'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FreeTemporaryEmailGeneratorRouteImport } from './routes/free-temporary-email-generator'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisposableEmailForVerificationRouteImport } from './routes/disposable-email-for-verification'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WhatIsTemporaryEmailRoute = WhatIsTemporaryEmailRouteImport.update({
  id: '/what-is-temporary-email',
  path: '/what-is-temporary-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TempMailForTiktokRoute = TempMailForTiktokRouteImport.update({
  id: '/temp-mail-for-tiktok',
  path: '/temp-mail-for-tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const TempMailForOtpRoute = TempMailForOtpRouteImport.update({
  id: '/temp-mail-for-otp',
  path: '/temp-mail-for-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TempMailForNetflixRoute = TempMailForNetflixRouteImport.update({
  id: '/temp-mail-for-netflix',
  path: '/temp-mail-for-netflix',
  getParentRoute: () => rootRouteImport,
} as any)
const TempMailForInstagramRoute = TempMailForInstagramRouteImport.update({
  id: '/temp-mail-for-instagram',
  path: '/temp-mail-for-instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const TempMailForAmazonRoute = TempMailForAmazonRouteImport.update({
  id: '/temp-mail-for-amazon',
  path: '/temp-mail-for-amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeTemporaryEmailGeneratorRoute =
  FreeTemporaryEmailGeneratorRouteImport.update({
    id: '/free-temporary-email-generator',
    path: '/free-temporary-email-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisposableEmailForVerificationRoute =
  DisposableEmailForVerificationRouteImport.update({
    id: '/disposable-email-for-verification',
    path: '/disposable-email-for-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/disposable-email-for-verification': typeof DisposableEmailForVerificationRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/free-temporary-email-generator': typeof FreeTemporaryEmailGeneratorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/temp-mail-for-amazon': typeof TempMailForAmazonRoute
  '/temp-mail-for-instagram': typeof TempMailForInstagramRoute
  '/temp-mail-for-netflix': typeof TempMailForNetflixRoute
  '/temp-mail-for-otp': typeof TempMailForOtpRoute
  '/temp-mail-for-tiktok': typeof TempMailForTiktokRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/use-cases': typeof UseCasesRoute
  '/what-is-temporary-email': typeof WhatIsTemporaryEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/disposable-email-for-verification': typeof DisposableEmailForVerificationRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/free-temporary-email-generator': typeof FreeTemporaryEmailGeneratorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/temp-mail-for-amazon': typeof TempMailForAmazonRoute
  '/temp-mail-for-instagram': typeof TempMailForInstagramRoute
  '/temp-mail-for-netflix': typeof TempMailForNetflixRoute
  '/temp-mail-for-otp': typeof TempMailForOtpRoute
  '/temp-mail-for-tiktok': typeof TempMailForTiktokRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/use-cases': typeof UseCasesRoute
  '/what-is-temporary-email': typeof WhatIsTemporaryEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/disposable-email-for-verification': typeof DisposableEmailForVerificationRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/free-temporary-email-generator': typeof FreeTemporaryEmailGeneratorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/temp-mail-for-amazon': typeof TempMailForAmazonRoute
  '/temp-mail-for-instagram': typeof TempMailForInstagramRoute
  '/temp-mail-for-netflix': typeof TempMailForNetflixRoute
  '/temp-mail-for-otp': typeof TempMailForOtpRoute
  '/temp-mail-for-tiktok': typeof TempMailForTiktokRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/use-cases': typeof UseCasesRoute
  '/what-is-temporary-email': typeof WhatIsTemporaryEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/disposable-email-for-verification'
    | '/faq'
    | '/features'
    | '/free-temporary-email-generator'
    | '/how-it-works'
    | '/privacy-policy'
    | '/temp-mail-for-amazon'
    | '/temp-mail-for-instagram'
    | '/temp-mail-for-netflix'
    | '/temp-mail-for-otp'
    | '/temp-mail-for-tiktok'
    | '/terms-of-service'
    | '/use-cases'
    | '/what-is-temporary-email'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/disposable-email-for-verification'
    | '/faq'
    | '/features'
    | '/free-temporary-email-generator'
    | '/how-it-works'
    | '/privacy-policy'
    | '/temp-mail-for-amazon'
    | '/temp-mail-for-instagram'
    | '/temp-mail-for-netflix'
    | '/temp-mail-for-otp'
    | '/temp-mail-for-tiktok'
    | '/terms-of-service'
    | '/use-cases'
    | '/what-is-temporary-email'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/disposable-email-for-verification'
    | '/faq'
    | '/features'
    | '/free-temporary-email-generator'
    | '/how-it-works'
    | '/privacy-policy'
    | '/temp-mail-for-amazon'
    | '/temp-mail-for-instagram'
    | '/temp-mail-for-netflix'
    | '/temp-mail-for-otp'
    | '/temp-mail-for-tiktok'
    | '/terms-of-service'
    | '/use-cases'
    | '/what-is-temporary-email'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DisposableEmailForVerificationRoute: typeof DisposableEmailForVerificationRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  FreeTemporaryEmailGeneratorRoute: typeof FreeTemporaryEmailGeneratorRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TempMailForAmazonRoute: typeof TempMailForAmazonRoute
  TempMailForInstagramRoute: typeof TempMailForInstagramRoute
  TempMailForNetflixRoute: typeof TempMailForNetflixRoute
  TempMailForOtpRoute: typeof TempMailForOtpRoute
  TempMailForTiktokRoute: typeof TempMailForTiktokRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  UseCasesRoute: typeof UseCasesRoute
  WhatIsTemporaryEmailRoute: typeof WhatIsTemporaryEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-temporary-email': {
      id: '/what-is-temporary-email'
      path: '/what-is-temporary-email'
      fullPath: '/what-is-temporary-email'
      preLoaderRoute: typeof WhatIsTemporaryEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp-mail-for-tiktok': {
      id: '/temp-mail-for-tiktok'
      path: '/temp-mail-for-tiktok'
      fullPath: '/temp-mail-for-tiktok'
      preLoaderRoute: typeof TempMailForTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp-mail-for-otp': {
      id: '/temp-mail-for-otp'
      path: '/temp-mail-for-otp'
      fullPath: '/temp-mail-for-otp'
      preLoaderRoute: typeof TempMailForOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp-mail-for-netflix': {
      id: '/temp-mail-for-netflix'
      path: '/temp-mail-for-netflix'
      fullPath: '/temp-mail-for-netflix'
      preLoaderRoute: typeof TempMailForNetflixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp-mail-for-instagram': {
      id: '/temp-mail-for-instagram'
      path: '/temp-mail-for-instagram'
      fullPath: '/temp-mail-for-instagram'
      preLoaderRoute: typeof TempMailForInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp-mail-for-amazon': {
      id: '/temp-mail-for-amazon'
      path: '/temp-mail-for-amazon'
      fullPath: '/temp-mail-for-amazon'
      preLoaderRoute: typeof TempMailForAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-temporary-email-generator': {
      id: '/free-temporary-email-generator'
      path: '/free-temporary-email-generator'
      fullPath: '/free-temporary-email-generator'
      preLoaderRoute: typeof FreeTemporaryEmailGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disposable-email-for-verification': {
      id: '/disposable-email-for-verification'
      path: '/disposable-email-for-verification'
      fullPath: '/disposable-email-for-verification'
      preLoaderRoute: typeof DisposableEmailForVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  DisposableEmailForVerificationRoute: DisposableEmailForVerificationRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  FreeTemporaryEmailGeneratorRoute: FreeTemporaryEmailGeneratorRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TempMailForAmazonRoute: TempMailForAmazonRoute,
  TempMailForInstagramRoute: TempMailForInstagramRoute,
  TempMailForNetflixRoute: TempMailForNetflixRoute,
  TempMailForOtpRoute: TempMailForOtpRoute,
  TempMailForTiktokRoute: TempMailForTiktokRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UseCasesRoute: UseCasesRoute,
  WhatIsTemporaryEmailRoute: WhatIsTemporaryEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
